name: pointer_teachers_v2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  pin_entry_text_field: ^0.1.4
  firebase_core: ^1.4.0
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.2.0
  fluttertoast: ^8.0.7
  cloud_firestore: ^3.2.1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutterfire_ui: ^0.4.2+2
  firebase_auth: ^3.4.1
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-SemiBold.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Bold.ttf
  assets:
    - images/
    - images/ranks/